I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 237, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/script.rpy", line 329, in script
    python:
  File "game/script.rpy", line 471, in <module>
    voice(audio_tts,volume=1.5)
TypeError: voice() got an unexpected keyword argument 'volume'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 237, in script call
    call _splashscreen from _call_splashscreen_1
  File "game/script.rpy", line 329, in script
    python:
  File "D:\Renpy\renpy-8.0.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Renpy\renpy-8.0.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 471, in <module>
    voice(audio_tts,volume=1.5)
TypeError: voice() got an unexpected keyword argument 'volume'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Amadeus 1.3.0
Sun Nov 12 23:19:08 2023
